# Generated by Django 3.2.18 on 2023-07-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_blogpost_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'User Post', 'verbose_name_plural': 'User Posts'},
        ),
    ]
