# Generated by Django 3.2.18 on 2023-07-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0005_delete_userposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
