# Generated by Django 3.2.18 on 2023-08-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0007_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
